// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"bytes"
	"fmt"
	"io"
	"strconv"

	"github.com/omnivore-app/omnivore/internal/model"
)

type ArchiveLinkResult interface {
	IsArchiveLinkResult()
}

type ArticleResult interface {
	IsArticleResult()
}

type CreateHighlightResult interface {
	IsCreateHighlightResult()
}

type CreateLabelResult interface {
	IsCreateLabelResult()
}

type DeleteHighlightResult interface {
	IsDeleteHighlightResult()
}

type LabelsResult interface {
	IsLabelsResult()
}

type SaveResult interface {
	IsSaveResult()
}

type SearchResult interface {
	IsSearchResult()
}

type SetBookmarkArticleResult interface {
	IsSetBookmarkArticleResult()
}

type SetLabelsResult interface {
	IsSetLabelsResult()
}

type SubscribeResult interface {
	IsSubscribeResult()
}

type UpdateHighlightResult interface {
	IsUpdateHighlightResult()
}

type UpdatePageResult interface {
	IsUpdatePageResult()
}

type ArchiveLinkError struct {
	Message    *string                `json:"message,omitempty"`
	ErrorCodes []ArchiveLinkErrorCode `json:"errorCodes"`
}

func (ArchiveLinkError) IsArchiveLinkResult() {}

type ArchiveLinkInput struct {
	LinkID   string `json:"linkId"`
	Archived bool   `json:"archived"`
}

type ArchiveLinkSuccess struct {
	LinkID  string  `json:"linkId"`
	Message *string `json:"message,omitempty"`
}

func (ArchiveLinkSuccess) IsArchiveLinkResult() {}

type Article struct {
	ID                         string            `json:"id"`
	Slug                       string            `json:"slug"`
	Title                      *string           `json:"title,omitempty"`
	Author                     *string           `json:"author,omitempty"`
	Description                *string           `json:"description,omitempty"`
	URL                        string            `json:"url"`
	PageType                   PageType          `json:"pageType"`
	ContentReader              ContentReader     `json:"contentReader"`
	CreatedAt                  string            `json:"createdAt"`
	UpdatedAt                  *string           `json:"updatedAt,omitempty"`
	Image                      *string           `json:"image,omitempty"`
	State                      LibraryItemState  `json:"state"`
	SavedAt                    string            `json:"savedAt"`
	ReadAt                     *string           `json:"readAt,omitempty"`
	ArchivedAt                 *string           `json:"archivedAt,omitempty"`
	PublishedAt                *string           `json:"publishedAt,omitempty"`
	ReadingProgressPercent     float64           `json:"readingProgressPercent"`
	ReadingProgressTopPercent  *float64          `json:"readingProgressTopPercent,omitempty"`
	ReadingProgressAnchorIndex int32             `json:"readingProgressAnchorIndex"`
	OriginalArticleURL         *string           `json:"originalArticleUrl,omitempty"`
	UploadFileID               *string           `json:"uploadFileId,omitempty"`
	SiteName                   *string           `json:"siteName,omitempty"`
	SiteIcon                   *string           `json:"siteIcon,omitempty"`
	Subscription               *string           `json:"subscription,omitempty"`
	WordsCount                 *int32            `json:"wordsCount,omitempty"`
	Folder                     string            `json:"folder"`
	LinkID                     *string           `json:"linkId,omitempty"`
	Content                    string            `json:"content"`
	OriginalHTML               *string           `json:"originalHtml,omitempty"`
	Labels                     []*Label          `json:"labels"`
	Highlights                 []*Highlight      `json:"highlights"`
	Recommendations            []*Recommendation `json:"recommendations,omitempty"`
}

type ArticleError struct {
	ErrorCodes []ArticleErrorCode `json:"errorCodes"`
}

func (ArticleError) IsArticleResult() {}

type ArticleHighlightsInput struct {
	IncludeFriends *bool `json:"includeFriends,omitempty"`
}

type ArticleSuccess struct {
	Article *Article `json:"article"`
}

func (ArticleSuccess) IsArticleResult() {}

type CreateHighlightError struct {
	ErrorCodes []CreateHighlightErrorCode `json:"errorCodes"`
}

func (CreateHighlightError) IsCreateHighlightResult() {}

type CreateHighlightInput struct {
	ID         string  `json:"id"`
	ShortID    string  `json:"shortId"`
	ArticleID  string  `json:"articleId"`
	Quote      *string `json:"quote,omitempty"`
	Annotation *string `json:"annotation,omitempty"`
	Patch      *string `json:"patch,omitempty"`
	Color      *string `json:"color,omitempty"`
}

type CreateHighlightSuccess struct {
	Highlight *Highlight `json:"highlight"`
}

func (CreateHighlightSuccess) IsCreateHighlightResult() {}

type CreateLabelError struct {
	ErrorCodes []CreateLabelErrorCode `json:"errorCodes"`
}

func (CreateLabelError) IsCreateLabelResult() {}

type CreateLabelInput struct {
	Name        string  `json:"name"`
	Color       *string `json:"color,omitempty"`
	Description *string `json:"description,omitempty"`
}

type CreateLabelSuccess struct {
	Label *Label `json:"label"`
}

func (CreateLabelSuccess) IsCreateLabelResult() {}

type DeleteHighlightError struct {
	ErrorCodes []DeleteHighlightErrorCode `json:"errorCodes"`
}

func (DeleteHighlightError) IsDeleteHighlightResult() {}

type DeleteHighlightSuccess struct {
	Highlight *Highlight `json:"highlight"`
}

func (DeleteHighlightSuccess) IsDeleteHighlightResult() {}

type Feature struct {
	ID        string  `json:"id"`
	Name      string  `json:"name"`
	CreatedAt string  `json:"createdAt"`
	UpdatedAt string  `json:"updatedAt"`
	GrantedAt *string `json:"grantedAt,omitempty"`
	ExpiresAt *string `json:"expiresAt,omitempty"`
}

type Highlight struct {
	ID                           string   `json:"id"`
	Type                         string   `json:"type"`
	ShortID                      string   `json:"shortId"`
	Quote                        *string  `json:"quote,omitempty"`
	Prefix                       *string  `json:"prefix,omitempty"`
	Suffix                       *string  `json:"suffix,omitempty"`
	Patch                        *string  `json:"patch,omitempty"`
	Annotation                   *string  `json:"annotation,omitempty"`
	Color                        *string  `json:"color,omitempty"`
	CreatedByMe                  bool     `json:"createdByMe"`
	CreatedAt                    string   `json:"createdAt"`
	UpdatedAt                    string   `json:"updatedAt"`
	SharedAt                     *string  `json:"sharedAt,omitempty"`
	HighlightPositionPercent     *float64 `json:"highlightPositionPercent,omitempty"`
	HighlightPositionAnchorIndex *int32   `json:"highlightPositionAnchorIndex,omitempty"`
	Labels                       []*Label `json:"labels,omitempty"`
}

type Label struct {
	ID          string  `json:"id"`
	Name        string  `json:"name"`
	Color       string  `json:"color"`
	Description *string `json:"description,omitempty"`
	CreatedAt   *string `json:"createdAt,omitempty"`
}

type LabelsError struct {
	ErrorCodes []LabelsErrorCode `json:"errorCodes"`
}

func (LabelsError) IsLabelsResult() {}

type LabelsSuccess struct {
	Labels []*Label `json:"labels"`
}

func (LabelsSuccess) IsLabelsResult() {}

type LibraryItem struct {
	ID                         string           `json:"id"`
	Slug                       string           `json:"slug"`
	Title                      *string          `json:"title,omitempty"`
	Author                     *string          `json:"author,omitempty"`
	Description                *string          `json:"description,omitempty"`
	URL                        string           `json:"url"`
	PageID                     *string          `json:"pageId,omitempty"`
	PageType                   PageType         `json:"pageType"`
	ContentReader              ContentReader    `json:"contentReader"`
	CreatedAt                  string           `json:"createdAt"`
	UpdatedAt                  *string          `json:"updatedAt,omitempty"`
	Thumbnail                  *string          `json:"thumbnail,omitempty"`
	Image                      *string          `json:"image,omitempty"`
	State                      LibraryItemState `json:"state"`
	SavedAt                    string           `json:"savedAt"`
	ReadAt                     *string          `json:"readAt,omitempty"`
	ArchivedAt                 *string          `json:"archivedAt,omitempty"`
	PublishedAt                *string          `json:"publishedAt,omitempty"`
	ReadingProgressPercent     float64          `json:"readingProgressPercent"`
	ReadingProgressTopPercent  *float64         `json:"readingProgressTopPercent,omitempty"`
	ReadingProgressAnchorIndex int32            `json:"readingProgressAnchorIndex"`
	OwnedByViewer              *bool            `json:"ownedByViewer,omitempty"`
	OriginalArticleURL         *string          `json:"originalArticleUrl,omitempty"`
	UploadFileID               *string          `json:"uploadFileId,omitempty"`
	ShortID                    *string          `json:"shortId,omitempty"`
	Quote                      *string          `json:"quote,omitempty"`
	Annotation                 *string          `json:"annotation,omitempty"`
	SiteName                   *string          `json:"siteName,omitempty"`
	SiteIcon                   *string          `json:"siteIcon,omitempty"`
	Subscription               *string          `json:"subscription,omitempty"`
	WordsCount                 *int32           `json:"wordsCount,omitempty"`
	HighlightsCount            *int32           `json:"highlightsCount,omitempty"`
	Folder                     string           `json:"folder"`
	Labels                     []*Label         `json:"labels"`
	Highlights                 []*Highlight     `json:"highlights"`
}

type Mutation struct {
}

type PageInfo struct {
	HasNextPage     bool    `json:"hasNextPage"`
	HasPreviousPage bool    `json:"hasPreviousPage"`
	StartCursor     *string `json:"startCursor,omitempty"`
	EndCursor       *string `json:"endCursor,omitempty"`
	TotalCount      *int32  `json:"totalCount,omitempty"`
}

type Profile struct {
	ID         string  `json:"id"`
	Username   string  `json:"username"`
	Bio        *string `json:"bio,omitempty"`
	PictureURL *string `json:"pictureUrl,omitempty"`
}

type Query struct {
}

type Recommendation struct {
	ID            string            `json:"id"`
	Name          string            `json:"name"`
	Note          *string           `json:"note,omitempty"`
	User          *RecommendingUser `json:"user,omitempty"`
	RecommendedAt string            `json:"recommendedAt"`
}

type RecommendingUser struct {
	UserID          string  `json:"userId"`
	Name            string  `json:"name"`
	Username        string  `json:"username"`
	ProfileImageURL *string `json:"profileImageURL,omitempty"`
}

type SaveError struct {
	ErrorCodes []SaveErrorCode `json:"errorCodes"`
	Message    *string         `json:"message,omitempty"`
}

func (SaveError) IsSaveResult() {}

type SavePageInput struct {
	ClientRequestID *string `json:"clientRequestId,omitempty"`
	URL             string  `json:"url"`
	OriginalHTML    string  `json:"originalHtml"`
	Title           *string `json:"title,omitempty"`
	Source          *string `json:"source,omitempty"`
}

type SaveSuccess struct {
	URL             string `json:"url"`
	ClientRequestID string `json:"clientRequestId"`
}

func (SaveSuccess) IsSaveResult() {}

type SaveURLInput struct {
	ClientRequestID *string `json:"clientRequestId,omitempty"`
	URL             string  `json:"url"`
	Source          *string `json:"source,omitempty"`
	Timezone        *string `json:"timezone,omitempty"`
	Locale          *string `json:"locale,omitempty"`
}

type SearchError struct {
	ErrorCodes []SearchErrorCode `json:"errorCodes"`
}

func (SearchError) IsSearchResult() {}

type SearchItemEdge struct {
	Node   *LibraryItem `json:"node"`
	Cursor string       `json:"cursor"`
}

type SearchSuccess struct {
	Edges    []*SearchItemEdge `json:"edges"`
	PageInfo *PageInfo         `json:"pageInfo"`
}

func (SearchSuccess) IsSearchResult() {}

type SetBookmarkArticleError struct {
	ErrorCodes []SetBookmarkArticleErrorCode `json:"errorCodes"`
}

func (SetBookmarkArticleError) IsSetBookmarkArticleResult() {}

type SetBookmarkArticleInput struct {
	ArticleID string `json:"articleID"`
	Bookmark  bool   `json:"bookmark"`
}

type SetBookmarkArticleSuccess struct {
	BookmarkedArticle *Article `json:"bookmarkedArticle"`
}

func (SetBookmarkArticleSuccess) IsSetBookmarkArticleResult() {}

type SetLabelsError struct {
	ErrorCodes []SetLabelsErrorCode `json:"errorCodes"`
}

func (SetLabelsError) IsSetLabelsResult() {}

type SetLabelsInput struct {
	PageID   string   `json:"pageId"`
	LabelIds []string `json:"labelIds"`
}

type SetLabelsSuccess struct {
	Labels []*Label `json:"labels"`
}

func (SetLabelsSuccess) IsSetLabelsResult() {}

type SortParams struct {
	By    *SortBy    `json:"by,omitempty"`
	Order *SortOrder `json:"order,omitempty"`
}

type SubscribeError struct {
	ErrorCodes []SubscribeErrorCode `json:"errorCodes"`
}

func (SubscribeError) IsSubscribeResult() {}

type SubscribeInput struct {
	URL              string                  `json:"url"`
	SubscriptionType *model.SubscriptionType `json:"subscriptionType,omitempty"`
	IsPrivate        *bool                   `json:"isPrivate,omitempty"`
	AutoAddToLibrary *bool                   `json:"autoAddToLibrary,omitempty"`
	FetchContent     *bool                   `json:"fetchContent,omitempty"`
	FetchContentType *FetchContentType       `json:"fetchContentType,omitempty"`
	Folder           *string                 `json:"folder,omitempty"`
}

type SubscribeSuccess struct {
	Subscriptions []*model.Subscription `json:"subscriptions"`
}

func (SubscribeSuccess) IsSubscribeResult() {}

type UpdateHighlightError struct {
	ErrorCodes []UpdateHighlightErrorCode `json:"errorCodes"`
}

func (UpdateHighlightError) IsUpdateHighlightResult() {}

type UpdateHighlightInput struct {
	HighlightID string  `json:"highlightId"`
	Annotation  *string `json:"annotation,omitempty"`
	Color       *string `json:"color,omitempty"`
}

type UpdateHighlightSuccess struct {
	Highlight *Highlight `json:"highlight"`
}

func (UpdateHighlightSuccess) IsUpdateHighlightResult() {}

type UpdatePageError struct {
	ErrorCodes []UpdatePageErrorCode `json:"errorCodes"`
}

func (UpdatePageError) IsUpdatePageResult() {}

type UpdatePageInput struct {
	PageID                 string            `json:"pageId"`
	Title                  *string           `json:"title,omitempty"`
	Description            *string           `json:"description,omitempty"`
	SavedAt                *string           `json:"savedAt,omitempty"`
	ReadingProgressPercent *float64          `json:"readingProgressPercent,omitempty"`
	State                  *LibraryItemState `json:"state,omitempty"`
}

type UpdatePageSuccess struct {
	UpdatedPage *LibraryItem `json:"updatedPage"`
}

func (UpdatePageSuccess) IsUpdatePageResult() {}

type User struct {
	ID           string     `json:"id"`
	Name         string     `json:"name"`
	Email        *string    `json:"email,omitempty"`
	Source       *string    `json:"source,omitempty"`
	IntercomHash *string    `json:"intercomHash,omitempty"`
	IsFullUser   *bool      `json:"isFullUser,omitempty"`
	FeatureList  []*Feature `json:"featureList,omitempty"`
	Profile      *Profile   `json:"profile"`
}

type ArchiveLinkErrorCode string

const (
	ArchiveLinkErrorCodeBadRequest   ArchiveLinkErrorCode = "BAD_REQUEST"
	ArchiveLinkErrorCodeForbidden    ArchiveLinkErrorCode = "FORBIDDEN"
	ArchiveLinkErrorCodeNotFound     ArchiveLinkErrorCode = "NOT_FOUND"
	ArchiveLinkErrorCodeUnauthorized ArchiveLinkErrorCode = "UNAUTHORIZED"
	ArchiveLinkErrorCodeUpdateFailed ArchiveLinkErrorCode = "UPDATE_FAILED"
)

var AllArchiveLinkErrorCode = []ArchiveLinkErrorCode{
	ArchiveLinkErrorCodeBadRequest,
	ArchiveLinkErrorCodeForbidden,
	ArchiveLinkErrorCodeNotFound,
	ArchiveLinkErrorCodeUnauthorized,
	ArchiveLinkErrorCodeUpdateFailed,
}

func (e ArchiveLinkErrorCode) IsValid() bool {
	switch e {
	case ArchiveLinkErrorCodeBadRequest, ArchiveLinkErrorCodeForbidden, ArchiveLinkErrorCodeNotFound, ArchiveLinkErrorCodeUnauthorized, ArchiveLinkErrorCodeUpdateFailed:
		return true
	}
	return false
}

func (e ArchiveLinkErrorCode) String() string {
	return string(e)
}

func (e *ArchiveLinkErrorCode) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = ArchiveLinkErrorCode(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid ArchiveLinkErrorCode", str)
	}
	return nil
}

func (e ArchiveLinkErrorCode) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *ArchiveLinkErrorCode) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e ArchiveLinkErrorCode) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type ArticleErrorCode string

const (
	ArticleErrorCodeBadData      ArticleErrorCode = "BAD_DATA"
	ArticleErrorCodeNotFound     ArticleErrorCode = "NOT_FOUND"
	ArticleErrorCodeUnauthorized ArticleErrorCode = "UNAUTHORIZED"
)

var AllArticleErrorCode = []ArticleErrorCode{
	ArticleErrorCodeBadData,
	ArticleErrorCodeNotFound,
	ArticleErrorCodeUnauthorized,
}

func (e ArticleErrorCode) IsValid() bool {
	switch e {
	case ArticleErrorCodeBadData, ArticleErrorCodeNotFound, ArticleErrorCodeUnauthorized:
		return true
	}
	return false
}

func (e ArticleErrorCode) String() string {
	return string(e)
}

func (e *ArticleErrorCode) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = ArticleErrorCode(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid ArticleErrorCode", str)
	}
	return nil
}

func (e ArticleErrorCode) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *ArticleErrorCode) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e ArticleErrorCode) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type ContentReader string

const (
	ContentReaderWeb  ContentReader = "WEB"
	ContentReaderPDF  ContentReader = "PDF"
	ContentReaderEpub ContentReader = "EPUB"
)

var AllContentReader = []ContentReader{
	ContentReaderWeb,
	ContentReaderPDF,
	ContentReaderEpub,
}

func (e ContentReader) IsValid() bool {
	switch e {
	case ContentReaderWeb, ContentReaderPDF, ContentReaderEpub:
		return true
	}
	return false
}

func (e ContentReader) String() string {
	return string(e)
}

func (e *ContentReader) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = ContentReader(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid ContentReader", str)
	}
	return nil
}

func (e ContentReader) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *ContentReader) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e ContentReader) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type CreateHighlightErrorCode string

const (
	CreateHighlightErrorCodeAlreadyExists CreateHighlightErrorCode = "ALREADY_EXISTS"
	CreateHighlightErrorCodeBadData       CreateHighlightErrorCode = "BAD_DATA"
	CreateHighlightErrorCodeForbidden     CreateHighlightErrorCode = "FORBIDDEN"
	CreateHighlightErrorCodeNotFound      CreateHighlightErrorCode = "NOT_FOUND"
	CreateHighlightErrorCodeUnauthorized  CreateHighlightErrorCode = "UNAUTHORIZED"
)

var AllCreateHighlightErrorCode = []CreateHighlightErrorCode{
	CreateHighlightErrorCodeAlreadyExists,
	CreateHighlightErrorCodeBadData,
	CreateHighlightErrorCodeForbidden,
	CreateHighlightErrorCodeNotFound,
	CreateHighlightErrorCodeUnauthorized,
}

func (e CreateHighlightErrorCode) IsValid() bool {
	switch e {
	case CreateHighlightErrorCodeAlreadyExists, CreateHighlightErrorCodeBadData, CreateHighlightErrorCodeForbidden, CreateHighlightErrorCodeNotFound, CreateHighlightErrorCodeUnauthorized:
		return true
	}
	return false
}

func (e CreateHighlightErrorCode) String() string {
	return string(e)
}

func (e *CreateHighlightErrorCode) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = CreateHighlightErrorCode(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid CreateHighlightErrorCode", str)
	}
	return nil
}

func (e CreateHighlightErrorCode) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *CreateHighlightErrorCode) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e CreateHighlightErrorCode) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type CreateLabelErrorCode string

const (
	CreateLabelErrorCodeBadRequest         CreateLabelErrorCode = "BAD_REQUEST"
	CreateLabelErrorCodeLabelAlreadyExists CreateLabelErrorCode = "LABEL_ALREADY_EXISTS"
	CreateLabelErrorCodeNotFound           CreateLabelErrorCode = "NOT_FOUND"
	CreateLabelErrorCodeUnauthorized       CreateLabelErrorCode = "UNAUTHORIZED"
)

var AllCreateLabelErrorCode = []CreateLabelErrorCode{
	CreateLabelErrorCodeBadRequest,
	CreateLabelErrorCodeLabelAlreadyExists,
	CreateLabelErrorCodeNotFound,
	CreateLabelErrorCodeUnauthorized,
}

func (e CreateLabelErrorCode) IsValid() bool {
	switch e {
	case CreateLabelErrorCodeBadRequest, CreateLabelErrorCodeLabelAlreadyExists, CreateLabelErrorCodeNotFound, CreateLabelErrorCodeUnauthorized:
		return true
	}
	return false
}

func (e CreateLabelErrorCode) String() string {
	return string(e)
}

func (e *CreateLabelErrorCode) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = CreateLabelErrorCode(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid CreateLabelErrorCode", str)
	}
	return nil
}

func (e CreateLabelErrorCode) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *CreateLabelErrorCode) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e CreateLabelErrorCode) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type DeleteHighlightErrorCode string

const (
	DeleteHighlightErrorCodeForbidden    DeleteHighlightErrorCode = "FORBIDDEN"
	DeleteHighlightErrorCodeNotFound     DeleteHighlightErrorCode = "NOT_FOUND"
	DeleteHighlightErrorCodeUnauthorized DeleteHighlightErrorCode = "UNAUTHORIZED"
)

var AllDeleteHighlightErrorCode = []DeleteHighlightErrorCode{
	DeleteHighlightErrorCodeForbidden,
	DeleteHighlightErrorCodeNotFound,
	DeleteHighlightErrorCodeUnauthorized,
}

func (e DeleteHighlightErrorCode) IsValid() bool {
	switch e {
	case DeleteHighlightErrorCodeForbidden, DeleteHighlightErrorCodeNotFound, DeleteHighlightErrorCodeUnauthorized:
		return true
	}
	return false
}

func (e DeleteHighlightErrorCode) String() string {
	return string(e)
}

func (e *DeleteHighlightErrorCode) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = DeleteHighlightErrorCode(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid DeleteHighlightErrorCode", str)
	}
	return nil
}

func (e DeleteHighlightErrorCode) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *DeleteHighlightErrorCode) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e DeleteHighlightErrorCode) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type FetchContentType string

const (
	FetchContentTypeAlways    FetchContentType = "ALWAYS"
	FetchContentTypeNever     FetchContentType = "NEVER"
	FetchContentTypeWhenEmpty FetchContentType = "WHEN_EMPTY"
)

var AllFetchContentType = []FetchContentType{
	FetchContentTypeAlways,
	FetchContentTypeNever,
	FetchContentTypeWhenEmpty,
}

func (e FetchContentType) IsValid() bool {
	switch e {
	case FetchContentTypeAlways, FetchContentTypeNever, FetchContentTypeWhenEmpty:
		return true
	}
	return false
}

func (e FetchContentType) String() string {
	return string(e)
}

func (e *FetchContentType) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = FetchContentType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid FetchContentType", str)
	}
	return nil
}

func (e FetchContentType) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *FetchContentType) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e FetchContentType) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type LabelsErrorCode string

const (
	LabelsErrorCodeBadRequest   LabelsErrorCode = "BAD_REQUEST"
	LabelsErrorCodeNotFound     LabelsErrorCode = "NOT_FOUND"
	LabelsErrorCodeUnauthorized LabelsErrorCode = "UNAUTHORIZED"
)

var AllLabelsErrorCode = []LabelsErrorCode{
	LabelsErrorCodeBadRequest,
	LabelsErrorCodeNotFound,
	LabelsErrorCodeUnauthorized,
}

func (e LabelsErrorCode) IsValid() bool {
	switch e {
	case LabelsErrorCodeBadRequest, LabelsErrorCodeNotFound, LabelsErrorCodeUnauthorized:
		return true
	}
	return false
}

func (e LabelsErrorCode) String() string {
	return string(e)
}

func (e *LabelsErrorCode) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = LabelsErrorCode(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid LabelsErrorCode", str)
	}
	return nil
}

func (e LabelsErrorCode) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *LabelsErrorCode) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e LabelsErrorCode) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type LibraryItemState string

const (
	LibraryItemStateSucceeded  LibraryItemState = "SUCCEEDED"
	LibraryItemStateProcessing LibraryItemState = "PROCESSING"
	LibraryItemStateFailed     LibraryItemState = "FAILED"
	LibraryItemStateDeleted    LibraryItemState = "DELETED"
	LibraryItemStateArchived   LibraryItemState = "ARCHIVED"
)

var AllLibraryItemState = []LibraryItemState{
	LibraryItemStateSucceeded,
	LibraryItemStateProcessing,
	LibraryItemStateFailed,
	LibraryItemStateDeleted,
	LibraryItemStateArchived,
}

func (e LibraryItemState) IsValid() bool {
	switch e {
	case LibraryItemStateSucceeded, LibraryItemStateProcessing, LibraryItemStateFailed, LibraryItemStateDeleted, LibraryItemStateArchived:
		return true
	}
	return false
}

func (e LibraryItemState) String() string {
	return string(e)
}

func (e *LibraryItemState) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = LibraryItemState(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid LibraryItemState", str)
	}
	return nil
}

func (e LibraryItemState) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *LibraryItemState) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e LibraryItemState) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type PageType string

const (
	PageTypeArticle    PageType = "ARTICLE"
	PageTypeBook       PageType = "BOOK"
	PageTypeFile       PageType = "FILE"
	PageTypeProfile    PageType = "PROFILE"
	PageTypeWebsite    PageType = "WEBSITE"
	PageTypeHighlights PageType = "HIGHLIGHTS"
	PageTypeUnknown    PageType = "UNKNOWN"
)

var AllPageType = []PageType{
	PageTypeArticle,
	PageTypeBook,
	PageTypeFile,
	PageTypeProfile,
	PageTypeWebsite,
	PageTypeHighlights,
	PageTypeUnknown,
}

func (e PageType) IsValid() bool {
	switch e {
	case PageTypeArticle, PageTypeBook, PageTypeFile, PageTypeProfile, PageTypeWebsite, PageTypeHighlights, PageTypeUnknown:
		return true
	}
	return false
}

func (e PageType) String() string {
	return string(e)
}

func (e *PageType) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = PageType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid PageType", str)
	}
	return nil
}

func (e PageType) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *PageType) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e PageType) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type SaveErrorCode string

const (
	SaveErrorCodeEmbeddedHighlightFailed SaveErrorCode = "EMBEDDED_HIGHLIGHT_FAILED"
	SaveErrorCodeUnauthorized            SaveErrorCode = "UNAUTHORIZED"
	SaveErrorCodeUnknown                 SaveErrorCode = "UNKNOWN"
)

var AllSaveErrorCode = []SaveErrorCode{
	SaveErrorCodeEmbeddedHighlightFailed,
	SaveErrorCodeUnauthorized,
	SaveErrorCodeUnknown,
}

func (e SaveErrorCode) IsValid() bool {
	switch e {
	case SaveErrorCodeEmbeddedHighlightFailed, SaveErrorCodeUnauthorized, SaveErrorCodeUnknown:
		return true
	}
	return false
}

func (e SaveErrorCode) String() string {
	return string(e)
}

func (e *SaveErrorCode) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = SaveErrorCode(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid SaveErrorCode", str)
	}
	return nil
}

func (e SaveErrorCode) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *SaveErrorCode) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e SaveErrorCode) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type SearchErrorCode string

const (
	SearchErrorCodeQueryTooLong SearchErrorCode = "QUERY_TOO_LONG"
	SearchErrorCodeUnauthorized SearchErrorCode = "UNAUTHORIZED"
)

var AllSearchErrorCode = []SearchErrorCode{
	SearchErrorCodeQueryTooLong,
	SearchErrorCodeUnauthorized,
}

func (e SearchErrorCode) IsValid() bool {
	switch e {
	case SearchErrorCodeQueryTooLong, SearchErrorCodeUnauthorized:
		return true
	}
	return false
}

func (e SearchErrorCode) String() string {
	return string(e)
}

func (e *SearchErrorCode) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = SearchErrorCode(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid SearchErrorCode", str)
	}
	return nil
}

func (e SearchErrorCode) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *SearchErrorCode) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e SearchErrorCode) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type SetBookmarkArticleErrorCode string

const (
	SetBookmarkArticleErrorCodeNotFound       SetBookmarkArticleErrorCode = "NOT_FOUND"
	SetBookmarkArticleErrorCodeBookmarkExists SetBookmarkArticleErrorCode = "BOOKMARK_EXISTS"
)

var AllSetBookmarkArticleErrorCode = []SetBookmarkArticleErrorCode{
	SetBookmarkArticleErrorCodeNotFound,
	SetBookmarkArticleErrorCodeBookmarkExists,
}

func (e SetBookmarkArticleErrorCode) IsValid() bool {
	switch e {
	case SetBookmarkArticleErrorCodeNotFound, SetBookmarkArticleErrorCodeBookmarkExists:
		return true
	}
	return false
}

func (e SetBookmarkArticleErrorCode) String() string {
	return string(e)
}

func (e *SetBookmarkArticleErrorCode) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = SetBookmarkArticleErrorCode(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid SetBookmarkArticleErrorCode", str)
	}
	return nil
}

func (e SetBookmarkArticleErrorCode) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *SetBookmarkArticleErrorCode) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e SetBookmarkArticleErrorCode) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type SetLabelsErrorCode string

const (
	SetLabelsErrorCodeBadRequest   SetLabelsErrorCode = "BAD_REQUEST"
	SetLabelsErrorCodeNotFound     SetLabelsErrorCode = "NOT_FOUND"
	SetLabelsErrorCodeUnauthorized SetLabelsErrorCode = "UNAUTHORIZED"
)

var AllSetLabelsErrorCode = []SetLabelsErrorCode{
	SetLabelsErrorCodeBadRequest,
	SetLabelsErrorCodeNotFound,
	SetLabelsErrorCodeUnauthorized,
}

func (e SetLabelsErrorCode) IsValid() bool {
	switch e {
	case SetLabelsErrorCodeBadRequest, SetLabelsErrorCodeNotFound, SetLabelsErrorCodeUnauthorized:
		return true
	}
	return false
}

func (e SetLabelsErrorCode) String() string {
	return string(e)
}

func (e *SetLabelsErrorCode) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = SetLabelsErrorCode(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid SetLabelsErrorCode", str)
	}
	return nil
}

func (e SetLabelsErrorCode) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *SetLabelsErrorCode) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e SetLabelsErrorCode) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type SortBy string

const (
	SortByUpdatedTime SortBy = "UPDATED_TIME"
	SortByCreatedTime SortBy = "CREATED_TIME"
	SortByScore       SortBy = "SCORE"
	SortBySavedAt     SortBy = "SAVED_AT"
	SortByPublishedAt SortBy = "PUBLISHED_AT"
)

var AllSortBy = []SortBy{
	SortByUpdatedTime,
	SortByCreatedTime,
	SortByScore,
	SortBySavedAt,
	SortByPublishedAt,
}

func (e SortBy) IsValid() bool {
	switch e {
	case SortByUpdatedTime, SortByCreatedTime, SortByScore, SortBySavedAt, SortByPublishedAt:
		return true
	}
	return false
}

func (e SortBy) String() string {
	return string(e)
}

func (e *SortBy) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = SortBy(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid SortBy", str)
	}
	return nil
}

func (e SortBy) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *SortBy) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e SortBy) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type SortOrder string

const (
	SortOrderAscending  SortOrder = "ASCENDING"
	SortOrderDescending SortOrder = "DESCENDING"
)

var AllSortOrder = []SortOrder{
	SortOrderAscending,
	SortOrderDescending,
}

func (e SortOrder) IsValid() bool {
	switch e {
	case SortOrderAscending, SortOrderDescending:
		return true
	}
	return false
}

func (e SortOrder) String() string {
	return string(e)
}

func (e *SortOrder) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = SortOrder(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid SortOrder", str)
	}
	return nil
}

func (e SortOrder) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *SortOrder) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e SortOrder) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type SubscribeErrorCode string

const (
	SubscribeErrorCodeUnauthorized             SubscribeErrorCode = "UNAUTHORIZED"
	SubscribeErrorCodeBadRequest               SubscribeErrorCode = "BAD_REQUEST"
	SubscribeErrorCodeNotFound                 SubscribeErrorCode = "NOT_FOUND"
	SubscribeErrorCodeAlreadySubscribed        SubscribeErrorCode = "ALREADY_SUBSCRIBED"
	SubscribeErrorCodeExceededMaxSubscriptions SubscribeErrorCode = "EXCEEDED_MAX_SUBSCRIPTIONS"
)

var AllSubscribeErrorCode = []SubscribeErrorCode{
	SubscribeErrorCodeUnauthorized,
	SubscribeErrorCodeBadRequest,
	SubscribeErrorCodeNotFound,
	SubscribeErrorCodeAlreadySubscribed,
	SubscribeErrorCodeExceededMaxSubscriptions,
}

func (e SubscribeErrorCode) IsValid() bool {
	switch e {
	case SubscribeErrorCodeUnauthorized, SubscribeErrorCodeBadRequest, SubscribeErrorCodeNotFound, SubscribeErrorCodeAlreadySubscribed, SubscribeErrorCodeExceededMaxSubscriptions:
		return true
	}
	return false
}

func (e SubscribeErrorCode) String() string {
	return string(e)
}

func (e *SubscribeErrorCode) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = SubscribeErrorCode(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid SubscribeErrorCode", str)
	}
	return nil
}

func (e SubscribeErrorCode) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *SubscribeErrorCode) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e SubscribeErrorCode) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type UpdateHighlightErrorCode string

const (
	UpdateHighlightErrorCodeBadRequest   UpdateHighlightErrorCode = "BAD_REQUEST"
	UpdateHighlightErrorCodeForbidden    UpdateHighlightErrorCode = "FORBIDDEN"
	UpdateHighlightErrorCodeNotFound     UpdateHighlightErrorCode = "NOT_FOUND"
	UpdateHighlightErrorCodeUnauthorized UpdateHighlightErrorCode = "UNAUTHORIZED"
)

var AllUpdateHighlightErrorCode = []UpdateHighlightErrorCode{
	UpdateHighlightErrorCodeBadRequest,
	UpdateHighlightErrorCodeForbidden,
	UpdateHighlightErrorCodeNotFound,
	UpdateHighlightErrorCodeUnauthorized,
}

func (e UpdateHighlightErrorCode) IsValid() bool {
	switch e {
	case UpdateHighlightErrorCodeBadRequest, UpdateHighlightErrorCodeForbidden, UpdateHighlightErrorCodeNotFound, UpdateHighlightErrorCodeUnauthorized:
		return true
	}
	return false
}

func (e UpdateHighlightErrorCode) String() string {
	return string(e)
}

func (e *UpdateHighlightErrorCode) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = UpdateHighlightErrorCode(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid UpdateHighlightErrorCode", str)
	}
	return nil
}

func (e UpdateHighlightErrorCode) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *UpdateHighlightErrorCode) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e UpdateHighlightErrorCode) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type UpdatePageErrorCode string

const (
	UpdatePageErrorCodeBadRequest   UpdatePageErrorCode = "BAD_REQUEST"
	UpdatePageErrorCodeForbidden    UpdatePageErrorCode = "FORBIDDEN"
	UpdatePageErrorCodeNotFound     UpdatePageErrorCode = "NOT_FOUND"
	UpdatePageErrorCodeUnauthorized UpdatePageErrorCode = "UNAUTHORIZED"
	UpdatePageErrorCodeUpdateFailed UpdatePageErrorCode = "UPDATE_FAILED"
)

var AllUpdatePageErrorCode = []UpdatePageErrorCode{
	UpdatePageErrorCodeBadRequest,
	UpdatePageErrorCodeForbidden,
	UpdatePageErrorCodeNotFound,
	UpdatePageErrorCodeUnauthorized,
	UpdatePageErrorCodeUpdateFailed,
}

func (e UpdatePageErrorCode) IsValid() bool {
	switch e {
	case UpdatePageErrorCodeBadRequest, UpdatePageErrorCodeForbidden, UpdatePageErrorCodeNotFound, UpdatePageErrorCodeUnauthorized, UpdatePageErrorCodeUpdateFailed:
		return true
	}
	return false
}

func (e UpdatePageErrorCode) String() string {
	return string(e)
}

func (e *UpdatePageErrorCode) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = UpdatePageErrorCode(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid UpdatePageErrorCode", str)
	}
	return nil
}

func (e UpdatePageErrorCode) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *UpdatePageErrorCode) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e UpdatePageErrorCode) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
