package resolver

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.88

import (
	"context"
	"fmt"
	"strings"
	"time"

	"github.com/google/uuid"
	"github.com/mmcdole/gofeed"
	"github.com/omnivore-app/omnivore/internal/db"
	"github.com/omnivore-app/omnivore/internal/graphql/generated"
	"github.com/omnivore-app/omnivore/internal/graphql/model"
	dbmodel "github.com/omnivore-app/omnivore/internal/model"
	"github.com/omnivore-app/omnivore/internal/service"
)

// SaveURL is the resolver for the saveUrl field.
func (r *mutationResolver) SaveURL(ctx context.Context, input model.SaveURLInput) (model.SaveResult, error) {
	// Get authenticated user
	user, hasUser := db.GetUserFromContext(ctx)
	if !hasUser {
		return &model.SaveError{
			ErrorCodes: []model.SaveErrorCode{model.SaveErrorCodeUnauthorized},
		}, nil
	}

	userID, err := uuid.Parse(user.ID)
	if err != nil {
		return &model.SaveError{
			ErrorCodes: []model.SaveErrorCode{model.SaveErrorCodeUnknown},
			Message:    strPtr(fmt.Sprintf("invalid user ID: %v", err)),
		}, nil
	}

	// Prepare service input
	source := "api"
	if input.Source != nil {
		source = *input.Source
	}

	saveInput := service.SaveURLInput{
		UserID:          userID,
		URL:             input.URL,
		Source:          source,
		ClientRequestID: uuid.New().String(),
		Timezone:        input.Timezone,
		Locale:          input.Locale,
	}
	if input.ClientRequestID != nil {
		saveInput.ClientRequestID = *input.ClientRequestID
	}

	// Call service
	result, err := r.SaveURLService.SaveURL(ctx, saveInput)
	if err != nil {
		return &model.SaveError{
			ErrorCodes: []model.SaveErrorCode{model.SaveErrorCodeUnknown},
			Message:    strPtr(fmt.Sprintf("failed to save URL: %v", err)),
		}, nil
	}

	return &model.SaveSuccess{
		URL:             result.URL,
		ClientRequestID: result.ClientRequestID,
	}, nil
}

// SavePage is the resolver for the savePage field.
func (r *mutationResolver) SavePage(ctx context.Context, input model.SavePageInput) (model.SaveResult, error) {
	// Get authenticated user
	user, hasUser := db.GetUserFromContext(ctx)
	if !hasUser {
		return &model.SaveError{
			ErrorCodes: []model.SaveErrorCode{model.SaveErrorCodeUnauthorized},
		}, nil
	}

	userID, err := uuid.Parse(user.ID)
	if err != nil {
		return &model.SaveError{
			ErrorCodes: []model.SaveErrorCode{model.SaveErrorCodeUnknown},
			Message:    strPtr(fmt.Sprintf("invalid user ID: %v", err)),
		}, nil
	}

	// Check if storage is configured
	if r.SavePageService == nil {
		return &model.SaveError{
			ErrorCodes: []model.SaveErrorCode{model.SaveErrorCodeUnknown},
			Message:    strPtr("storage not configured: HTML upload requires a working blob storage backend"),
		}, nil
	}

	// Prepare service input
	source := "api"
	if input.Source != nil {
		source = *input.Source
	}

	saveInput := service.SavePageInput{
		UserID:       userID,
		URL:          input.URL,
		OriginalHTML: input.OriginalHTML,
		Title:        input.Title,
		Source:       source,
	}
	if input.ClientRequestID != nil {
		saveInput.ClientRequestID = *input.ClientRequestID
	}

	// Call service
	result, err := r.SavePageService.SavePage(ctx, saveInput)
	if err != nil {
		return &model.SaveError{
			ErrorCodes: []model.SaveErrorCode{model.SaveErrorCodeUnknown},
			Message:    strPtr(fmt.Sprintf("failed to save page: %v", err)),
		}, nil
	}

	return &model.SaveSuccess{
		URL:             result.URL,
		ClientRequestID: result.ClientRequestID,
	}, nil
}

// CreateLabel is the resolver for the createLabel field.
func (r *mutationResolver) CreateLabel(ctx context.Context, input model.CreateLabelInput) (model.CreateLabelResult, error) {
	// Get authenticated user
	user, hasUser := db.GetUserFromContext(ctx)
	if !hasUser {
		return &model.CreateLabelError{
			ErrorCodes: []model.CreateLabelErrorCode{model.CreateLabelErrorCodeUnauthorized},
		}, nil
	}

	userID, err := uuid.Parse(user.ID)
	if err != nil {
		return &model.CreateLabelError{
			ErrorCodes: []model.CreateLabelErrorCode{model.CreateLabelErrorCodeBadRequest},
		}, nil
	}

	// Check for existing label with same name (case-insensitive)
	existing, err := r.LabelRepo.FindByName(ctx, userID, input.Name)
	if err != nil {
		return &model.CreateLabelError{
			ErrorCodes: []model.CreateLabelErrorCode{model.CreateLabelErrorCodeBadRequest},
		}, nil
	}
	if existing != nil {
		return &model.CreateLabelError{
			ErrorCodes: []model.CreateLabelErrorCode{model.CreateLabelErrorCodeLabelAlreadyExists},
		}, nil
	}

	// Create new label
	color := "#3B82F6" // Default blue
	if input.Color != nil {
		color = *input.Color
	}

	label := &dbmodel.Label{
		ID:     uuid.New(),
		UserID: userID,
		Name:   input.Name,
		Color:  color,
	}
	if input.Description != nil {
		label.Description = input.Description
	}

	if err := r.LabelRepo.Create(ctx, label); err != nil {
		return &model.CreateLabelError{
			ErrorCodes: []model.CreateLabelErrorCode{model.CreateLabelErrorCodeBadRequest},
		}, nil
	}

	// Convert to GraphQL model
	gqlLabel := &model.Label{
		ID:          label.ID.String(),
		Name:        label.Name,
		Color:       label.Color,
		Description: label.Description,
	}

	return &model.CreateLabelSuccess{
		Label: gqlLabel,
	}, nil
}

// SetLabels is the resolver for the setLabels field.
func (r *mutationResolver) SetLabels(ctx context.Context, input model.SetLabelsInput) (model.SetLabelsResult, error) {
	// Get authenticated user
	user, hasUser := db.GetUserFromContext(ctx)
	if !hasUser {
		return &model.SetLabelsError{
			ErrorCodes: []model.SetLabelsErrorCode{model.SetLabelsErrorCodeUnauthorized},
		}, nil
	}

	userID, err := uuid.Parse(user.ID)
	if err != nil {
		return &model.SetLabelsError{
			ErrorCodes: []model.SetLabelsErrorCode{model.SetLabelsErrorCodeBadRequest},
		}, nil
	}

	pageID, err := uuid.Parse(input.PageID)
	if err != nil {
		return &model.SetLabelsError{
			ErrorCodes: []model.SetLabelsErrorCode{model.SetLabelsErrorCodeBadRequest},
		}, nil
	}

	// Verify library item ownership
	item, err := r.LibraryItemRepo.GetByID(ctx, pageID)
	if err != nil {
		return &model.SetLabelsError{
			ErrorCodes: []model.SetLabelsErrorCode{model.SetLabelsErrorCodeNotFound},
		}, nil
	}
	if item.UserID != userID {
		return &model.SetLabelsError{
			ErrorCodes: []model.SetLabelsErrorCode{model.SetLabelsErrorCodeBadRequest},
		}, nil
	}

	// Parse label IDs
	labelIDs := make([]uuid.UUID, len(input.LabelIds))
	for i, id := range input.LabelIds {
		labelID, err := uuid.Parse(id)
		if err != nil {
			return &model.SetLabelsError{
				ErrorCodes: []model.SetLabelsErrorCode{model.SetLabelsErrorCodeBadRequest},
			}, nil
		}
		labelIDs[i] = labelID
	}

	// Set labels on library item
	if err := r.LibraryItemRepo.SetLabels(ctx, pageID, labelIDs); err != nil {
		return &model.SetLabelsError{
			ErrorCodes: []model.SetLabelsErrorCode{model.SetLabelsErrorCodeBadRequest},
		}, nil
	}

	// Fetch updated labels
	labels, err := r.LabelRepo.GetByIDs(ctx, labelIDs)
	if err != nil {
		return &model.SetLabelsError{
			ErrorCodes: []model.SetLabelsErrorCode{model.SetLabelsErrorCodeBadRequest},
		}, nil
	}

	// Convert to GraphQL models
	var gqlLabels []*model.Label
	for _, label := range labels {
		gqlLabels = append(gqlLabels, &model.Label{
			ID:          label.ID.String(),
			Name:        label.Name,
			Color:       label.Color,
			Description: label.Description,
		})
	}

	return &model.SetLabelsSuccess{
		Labels: gqlLabels,
	}, nil
}

// SetBookmarkArticle is the resolver for the setBookmarkArticle field.
func (r *mutationResolver) SetBookmarkArticle(ctx context.Context, input model.SetBookmarkArticleInput) (model.SetBookmarkArticleResult, error) {
	user, hasUser := db.GetUserFromContext(ctx)
	if !hasUser {
		return &model.SetBookmarkArticleError{
			ErrorCodes: []model.SetBookmarkArticleErrorCode{model.SetBookmarkArticleErrorCodeNotFound},
		}, nil
	}

	userID, err := uuid.Parse(user.ID)
	if err != nil {
		return &model.SetBookmarkArticleError{
			ErrorCodes: []model.SetBookmarkArticleErrorCode{model.SetBookmarkArticleErrorCodeNotFound},
		}, nil
	}

	articleID, err := uuid.Parse(input.ArticleID)
	if err != nil {
		return &model.SetBookmarkArticleError{
			ErrorCodes: []model.SetBookmarkArticleErrorCode{model.SetBookmarkArticleErrorCodeNotFound},
		}, nil
	}

	item, err := r.LibraryItemRepo.GetByID(ctx, articleID)
	if err != nil {
		return &model.SetBookmarkArticleError{
			ErrorCodes: []model.SetBookmarkArticleErrorCode{model.SetBookmarkArticleErrorCodeNotFound},
		}, nil
	}
	if item.UserID != userID {
		return &model.SetBookmarkArticleError{
			ErrorCodes: []model.SetBookmarkArticleErrorCode{model.SetBookmarkArticleErrorCodeNotFound},
		}, nil
	}

	if !input.Bookmark {
		item.State = dbmodel.LibraryItemStateDeleted
		if err := r.LibraryItemRepo.Update(ctx, item); err != nil {
			return nil, fmt.Errorf("failed to update bookmark state: %w", err)
		}
	}

	updatedItem, err := r.LibraryItemRepo.GetByID(ctx, articleID)
	if err != nil {
		updatedItem = item
	}

	return &model.SetBookmarkArticleSuccess{
		BookmarkedArticle: articleToGraphQL(updatedItem),
	}, nil
}

// SetLinkArchived is the resolver for the setLinkArchived field.
func (r *mutationResolver) SetLinkArchived(ctx context.Context, input model.ArchiveLinkInput) (model.ArchiveLinkResult, error) {
	user, hasUser := db.GetUserFromContext(ctx)
	if !hasUser {
		msg := "authentication required"
		return &model.ArchiveLinkError{
			Message:    &msg,
			ErrorCodes: []model.ArchiveLinkErrorCode{model.ArchiveLinkErrorCodeUnauthorized},
		}, nil
	}

	userID, err := uuid.Parse(user.ID)
	if err != nil {
		msg := "invalid user ID"
		return &model.ArchiveLinkError{
			Message:    &msg,
			ErrorCodes: []model.ArchiveLinkErrorCode{model.ArchiveLinkErrorCodeBadRequest},
		}, nil
	}

	linkID, err := uuid.Parse(input.LinkID)
	if err != nil {
		msg := "invalid link ID"
		return &model.ArchiveLinkError{
			Message:    &msg,
			ErrorCodes: []model.ArchiveLinkErrorCode{model.ArchiveLinkErrorCodeBadRequest},
		}, nil
	}

	item, err := r.LibraryItemRepo.GetByID(ctx, linkID)
	if err != nil {
		msg := "link not found"
		return &model.ArchiveLinkError{
			Message:    &msg,
			ErrorCodes: []model.ArchiveLinkErrorCode{model.ArchiveLinkErrorCodeNotFound},
		}, nil
	}
	if item.UserID != userID {
		msg := "link not found"
		return &model.ArchiveLinkError{
			Message:    &msg,
			ErrorCodes: []model.ArchiveLinkErrorCode{model.ArchiveLinkErrorCodeNotFound},
		}, nil
	}

	now := time.Now()
	if input.Archived {
		item.State = dbmodel.LibraryItemStateArchived
		item.ArchivedAt = &now
	} else {
		item.State = dbmodel.LibraryItemStateSucceeded
		item.ArchivedAt = nil
	}

	if err := r.LibraryItemRepo.Update(ctx, item); err != nil {
		msg := "failed to update archive state"
		return &model.ArchiveLinkError{
			Message:    &msg,
			ErrorCodes: []model.ArchiveLinkErrorCode{model.ArchiveLinkErrorCodeUpdateFailed},
		}, nil
	}

	msg := "Link archived"
	if !input.Archived {
		msg = "Link unarchived"
	}

	return &model.ArchiveLinkSuccess{
		LinkID:  input.LinkID,
		Message: &msg,
	}, nil
}

// Subscribe is the resolver for the subscribe field.
func (r *mutationResolver) Subscribe(ctx context.Context, input model.SubscribeInput) (model.SubscribeResult, error) {
	user, hasUser := db.GetUserFromContext(ctx)
	if !hasUser {
		return &model.SubscribeError{
			ErrorCodes: []model.SubscribeErrorCode{model.SubscribeErrorCodeUnauthorized},
		}, nil
	}

	userID, err := uuid.Parse(user.ID)
	if err != nil {
		return &model.SubscribeError{
			ErrorCodes: []model.SubscribeErrorCode{model.SubscribeErrorCodeBadRequest},
		}, nil
	}

	if input.SubscriptionType != nil && *input.SubscriptionType != dbmodel.SubscriptionTypeRSS {
		return &model.SubscribeError{
			ErrorCodes: []model.SubscribeErrorCode{model.SubscribeErrorCodeBadRequest},
		}, nil
	}

	if err := validateSubscriptionURL(input.URL); err != nil {
		return &model.SubscribeError{
			ErrorCodes: []model.SubscribeErrorCode{model.SubscribeErrorCodeBadRequest},
		}, nil
	}

	feed, err := gofeed.NewParser().ParseURL(input.URL)
	if err != nil || feed == nil {
		return &model.SubscribeError{
			ErrorCodes: []model.SubscribeErrorCode{model.SubscribeErrorCodeNotFound},
		}, nil
	}

	feedURL := canonicalFeedURL(input.URL, feed)
	candidateURLs := uniqueStrings([]string{input.URL, feedURL})

	existing, err := r.SubscriptionRepo.FindRSSByUserAndURLs(ctx, userID, candidateURLs)
	if err != nil {
		return nil, fmt.Errorf("failed to lookup subscription: %w", err)
	}

	fetchContentType := subscribeFetchContentType(input.FetchContentType)
	fetchContent := subscribeFetchContentValue(input.FetchContent, fetchContentType)
	folder := "following"
	if input.Folder != nil && strings.TrimSpace(*input.Folder) != "" {
		folder = strings.TrimSpace(*input.Folder)
	}

	if existing != nil {
		if existing.Status == dbmodel.SubscriptionStatusActive {
			return &model.SubscribeError{
				ErrorCodes: []model.SubscribeErrorCode{model.SubscribeErrorCodeAlreadySubscribed},
			}, nil
		}

		existing.Name = subscribeFeedName(feed, feedURL)
		existing.URL = strPtr(feedURL)
		existing.Description = emptyStringPtr(feed.Description)
		existing.Icon = subscribeFeedIcon(feed)
		existing.Status = dbmodel.SubscriptionStatusActive
		existing.Type = dbmodel.SubscriptionTypeRSS
		existing.FetchContentType = fetchContentType
		existing.FetchContent = fetchContent
		existing.Folder = folder
		existing.IsPrivate = input.IsPrivate
		if input.AutoAddToLibrary != nil {
			existing.AutoAddToLibrary = *input.AutoAddToLibrary
		}

		if err := r.SubscriptionRepo.Save(ctx, existing); err != nil {
			return nil, fmt.Errorf("failed to update subscription: %w", err)
		}
		if err := enqueueRefreshFeed(ctx, r.RedisClient, userID, existing, feedURL); err != nil {
			return nil, fmt.Errorf("failed to enqueue refresh-feed job: %w", err)
		}

		return &model.SubscribeSuccess{Subscriptions: []*dbmodel.Subscription{existing}}, nil
	}

	count, err := r.SubscriptionRepo.CountActiveRSSByUser(ctx, userID)
	if err != nil {
		return nil, fmt.Errorf("failed to count subscriptions: %w", err)
	}
	if count >= 256 {
		return &model.SubscribeError{
			ErrorCodes: []model.SubscribeErrorCode{model.SubscribeErrorCodeExceededMaxSubscriptions},
		}, nil
	}

	subscription := &dbmodel.Subscription{
		UserID:           userID,
		Name:             subscribeFeedName(feed, feedURL),
		Description:      emptyStringPtr(feed.Description),
		URL:              strPtr(feedURL),
		Icon:             subscribeFeedIcon(feed),
		Status:           dbmodel.SubscriptionStatusActive,
		Type:             dbmodel.SubscriptionTypeRSS,
		FetchContentType: fetchContentType,
		FetchContent:     fetchContent,
		Folder:           folder,
		IsPrivate:        input.IsPrivate,
	}
	if input.AutoAddToLibrary != nil {
		subscription.AutoAddToLibrary = *input.AutoAddToLibrary
	}

	if err := r.SubscriptionRepo.Save(ctx, subscription); err != nil {
		return nil, fmt.Errorf("failed to create subscription: %w", err)
	}
	if err := enqueueRefreshFeed(ctx, r.RedisClient, userID, subscription, feedURL); err != nil {
		return nil, fmt.Errorf("failed to enqueue refresh-feed job: %w", err)
	}

	return &model.SubscribeSuccess{Subscriptions: []*dbmodel.Subscription{subscription}}, nil
}

// CreateHighlight is the resolver for the createHighlight field.
func (r *mutationResolver) CreateHighlight(ctx context.Context, input model.CreateHighlightInput) (model.CreateHighlightResult, error) {
	// Get authenticated user
	user, hasUser := db.GetUserFromContext(ctx)
	if !hasUser {
		return &model.CreateHighlightError{
			ErrorCodes: []model.CreateHighlightErrorCode{model.CreateHighlightErrorCodeUnauthorized},
		}, nil
	}

	userID, err := uuid.Parse(user.ID)
	if err != nil {
		return &model.CreateHighlightError{
			ErrorCodes: []model.CreateHighlightErrorCode{model.CreateHighlightErrorCodeNotFound},
		}, nil
	}

	highlightID, err := uuid.Parse(input.ID)
	if err != nil {
		return &model.CreateHighlightError{
			ErrorCodes: []model.CreateHighlightErrorCode{model.CreateHighlightErrorCodeNotFound},
		}, nil
	}

	articleID, err := uuid.Parse(input.ArticleID)
	if err != nil {
		return &model.CreateHighlightError{
			ErrorCodes: []model.CreateHighlightErrorCode{model.CreateHighlightErrorCodeNotFound},
		}, nil
	}

	// Verify library item ownership
	item, err := r.LibraryItemRepo.GetByID(ctx, articleID)
	if err != nil {
		return &model.CreateHighlightError{
			ErrorCodes: []model.CreateHighlightErrorCode{model.CreateHighlightErrorCodeNotFound},
		}, nil
	}
	if item.UserID != userID {
		return &model.CreateHighlightError{
			ErrorCodes: []model.CreateHighlightErrorCode{model.CreateHighlightErrorCodeForbidden},
		}, nil
	}

	// Create highlight
	highlightType := dbmodel.HighlightTypeHighlight
	highlight := &dbmodel.Highlight{
		ID:            highlightID,
		UserID:        userID,
		ShortID:       input.ShortID,
		LibraryItemID: articleID,
		HighlightType: &highlightType,
	}

	if input.Quote != nil {
		highlight.Quote = input.Quote
	}
	if input.Annotation != nil {
		highlight.Annotation = input.Annotation
	}
	if input.Patch != nil {
		highlight.Patch = input.Patch
	}
	if input.Color != nil {
		highlight.Color = input.Color
	}

	if err := r.HighlightRepo.Create(ctx, highlight); err != nil {
		return &model.CreateHighlightError{
			ErrorCodes: []model.CreateHighlightErrorCode{model.CreateHighlightErrorCodeBadData},
		}, nil
	}

	// Convert to GraphQL model
	gqlHighlight := &model.Highlight{
		ID:         highlight.ID.String(),
		Quote:      highlight.Quote,
		Annotation: highlight.Annotation,
		Color:      highlight.Color,
		CreatedAt:  highlight.CreatedAt.Format(time.RFC3339),
		UpdatedAt:  highlight.UpdatedAt.Format(time.RFC3339),
	}

	return &model.CreateHighlightSuccess{
		Highlight: gqlHighlight,
	}, nil
}

// UpdateHighlight is the resolver for the updateHighlight field.
func (r *mutationResolver) UpdateHighlight(ctx context.Context, input model.UpdateHighlightInput) (model.UpdateHighlightResult, error) {
	// Get authenticated user
	user, hasUser := db.GetUserFromContext(ctx)
	if !hasUser {
		return &model.UpdateHighlightError{
			ErrorCodes: []model.UpdateHighlightErrorCode{model.UpdateHighlightErrorCodeUnauthorized},
		}, nil
	}

	userID, err := uuid.Parse(user.ID)
	if err != nil {
		return &model.UpdateHighlightError{
			ErrorCodes: []model.UpdateHighlightErrorCode{model.UpdateHighlightErrorCodeBadRequest},
		}, nil
	}

	highlightID, err := uuid.Parse(input.HighlightID)
	if err != nil {
		return &model.UpdateHighlightError{
			ErrorCodes: []model.UpdateHighlightErrorCode{model.UpdateHighlightErrorCodeBadRequest},
		}, nil
	}

	// Fetch existing highlight
	highlight, err := r.HighlightRepo.GetByID(ctx, highlightID)
	if err != nil {
		return &model.UpdateHighlightError{
			ErrorCodes: []model.UpdateHighlightErrorCode{model.UpdateHighlightErrorCodeNotFound},
		}, nil
	}

	// Check ownership
	if highlight.UserID != userID {
		return &model.UpdateHighlightError{
			ErrorCodes: []model.UpdateHighlightErrorCode{model.UpdateHighlightErrorCodeForbidden},
		}, nil
	}

	// Update only allowed fields
	if input.Annotation != nil {
		highlight.Annotation = input.Annotation
	}
	if input.Color != nil {
		highlight.Color = input.Color
	}

	if err := r.HighlightRepo.Update(ctx, highlight); err != nil {
		return &model.UpdateHighlightError{
			ErrorCodes: []model.UpdateHighlightErrorCode{model.UpdateHighlightErrorCodeBadRequest},
		}, nil
	}

	// Convert to GraphQL model
	gqlHighlight := &model.Highlight{
		ID:         highlight.ID.String(),
		Quote:      highlight.Quote,
		Annotation: highlight.Annotation,
		Color:      highlight.Color,
		CreatedAt:  highlight.CreatedAt.Format(time.RFC3339),
		UpdatedAt:  highlight.UpdatedAt.Format(time.RFC3339),
	}

	return &model.UpdateHighlightSuccess{
		Highlight: gqlHighlight,
	}, nil
}

// DeleteHighlight is the resolver for the deleteHighlight field.
func (r *mutationResolver) DeleteHighlight(ctx context.Context, highlightID string) (model.DeleteHighlightResult, error) {
	// Get authenticated user
	_, hasUser := db.GetUserFromContext(ctx)
	if !hasUser {
		return &model.DeleteHighlightError{
			ErrorCodes: []model.DeleteHighlightErrorCode{model.DeleteHighlightErrorCodeUnauthorized},
		}, nil
	}

	highlightUUID, err := uuid.Parse(highlightID)
	if err != nil {
		return &model.DeleteHighlightError{
			ErrorCodes: []model.DeleteHighlightErrorCode{model.DeleteHighlightErrorCodeNotFound},
		}, nil
	}

	// Fetch existing highlight before deletion
	highlight, err := r.HighlightRepo.GetByID(ctx, highlightUUID)
	if err != nil {
		return &model.DeleteHighlightError{
			ErrorCodes: []model.DeleteHighlightErrorCode{model.DeleteHighlightErrorCodeNotFound},
		}, nil
	}

	if err := r.HighlightRepo.Delete(ctx, highlightUUID); err != nil {
		return &model.DeleteHighlightError{
			ErrorCodes: []model.DeleteHighlightErrorCode{model.DeleteHighlightErrorCodeForbidden},
		}, nil
	}

	// Return deleted highlight
	return &model.DeleteHighlightSuccess{
		Highlight: &model.Highlight{
			ID:         highlight.ID.String(),
			Quote:      highlight.Quote,
			Annotation: highlight.Annotation,
			Color:      highlight.Color,
			CreatedAt:  highlight.CreatedAt.Format(time.RFC3339),
			UpdatedAt:  highlight.UpdatedAt.Format(time.RFC3339),
		},
	}, nil
}

// UpdatePage is the resolver for the updatePage field.
func (r *mutationResolver) UpdatePage(ctx context.Context, input model.UpdatePageInput) (model.UpdatePageResult, error) {
	// Get authenticated user
	user, hasUser := db.GetUserFromContext(ctx)
	if !hasUser {
		return &model.UpdatePageError{
			ErrorCodes: []model.UpdatePageErrorCode{model.UpdatePageErrorCodeUnauthorized},
		}, nil
	}

	userID, err := uuid.Parse(user.ID)
	if err != nil {
		return &model.UpdatePageError{
			ErrorCodes: []model.UpdatePageErrorCode{model.UpdatePageErrorCodeBadRequest},
		}, nil
	}

	pageID, err := uuid.Parse(input.PageID)
	if err != nil {
		return &model.UpdatePageError{
			ErrorCodes: []model.UpdatePageErrorCode{model.UpdatePageErrorCodeBadRequest},
		}, nil
	}

	// Fetch existing library item
	item, err := r.LibraryItemRepo.GetByID(ctx, pageID)
	if err != nil {
		return &model.UpdatePageError{
			ErrorCodes: []model.UpdatePageErrorCode{model.UpdatePageErrorCodeNotFound},
		}, nil
	}

	// Check ownership
	if item.UserID != userID {
		return &model.UpdatePageError{
			ErrorCodes: []model.UpdatePageErrorCode{model.UpdatePageErrorCodeForbidden},
		}, nil
	}

	// Update fields (partial update)
	if input.Title != nil {
		item.Title = input.Title
	}
	if input.Description != nil {
		item.Description = input.Description
	}
	if input.ReadingProgressPercent != nil {
		item.ReadingProgressPercent = *input.ReadingProgressPercent
	}
	if input.State != nil {
		item.State = dbmodel.LibraryItemState(*input.State)

		// Set state-specific timestamps
		now := time.Now()
		switch *input.State {
		case model.LibraryItemStateArchived:
			item.ArchivedAt = &now
		}
	}
	if input.SavedAt != nil {
		savedAt, err := time.Parse(time.RFC3339, *input.SavedAt)
		if err != nil {
			return &model.UpdatePageError{
				ErrorCodes: []model.UpdatePageErrorCode{model.UpdatePageErrorCodeBadRequest},
			}, nil
		}
		item.SavedAt = savedAt
	}

	// Save updates using repository method
	if err := r.LibraryItemRepo.Update(ctx, item); err != nil {
		return &model.UpdatePageError{
			ErrorCodes: []model.UpdatePageErrorCode{model.UpdatePageErrorCodeUpdateFailed},
		}, nil
	}

	// Reload item with relationships
	updatedItem, err := r.LibraryItemRepo.GetByID(ctx, pageID)
	if err != nil {
		return &model.UpdatePageError{
			ErrorCodes: []model.UpdatePageErrorCode{model.UpdatePageErrorCodeNotFound},
		}, nil
	}

	return &model.UpdatePageSuccess{
		UpdatedPage: libraryItemToGraphQL(updatedItem),
	}, nil
}

// Hello is the resolver for the hello field.
func (r *queryResolver) Hello(ctx context.Context) (string, error) {
	return "hello world", nil
}

// Me is the resolver for the me field.
func (r *queryResolver) Me(ctx context.Context) (*model.User, error) {
	// Get user from context (already authenticated by auth middleware)
	user, hasUser := db.GetUserFromContext(ctx)
	if !hasUser {
		return nil, fmt.Errorf("no user in context")
	}

	// Parse user ID
	userID, err := uuid.Parse(user.ID)
	if err != nil {
		return nil, fmt.Errorf("invalid user ID: %w", err)
	}

	// Fetch user from database
	dbUser, err := r.UserRepo.GetByID(ctx, userID)
	if err != nil {
		return nil, fmt.Errorf("failed to fetch user: %w", err)
	}

	// Convert to GraphQL model
	return &model.User{
		ID:    dbUser.ID.String(),
		Name:  dbUser.Name,
		Email: &dbUser.Email,
		Profile: &model.Profile{
			ID:       dbUser.Profile.ID.String(),
			Username: dbUser.Profile.Username,
		},
	}, nil
}

// Article is the resolver for the article field.
func (r *queryResolver) Article(ctx context.Context, id *string, slug *string, username *string) (model.ArticleResult, error) {
	// Must provide either id or slug
	if id == nil && slug == nil {
		return nil, fmt.Errorf("must provide either id or slug")
	}

	var dbItem *dbmodel.LibraryItem
	var err error

	if id != nil {
		itemID, parseErr := uuid.Parse(*id)
		if parseErr != nil {
			return nil, fmt.Errorf("invalid id format: %w", parseErr)
		}
		dbItem, err = r.LibraryItemRepo.GetByID(ctx, itemID)
	} else {
		dbItem, err = r.LibraryItemRepo.GetBySlug(ctx, *slug)
	}

	if err != nil {
		if strings.Contains(strings.ToLower(err.Error()), "not found") {
			return &model.ArticleError{
				ErrorCodes: []model.ArticleErrorCode{model.ArticleErrorCodeNotFound},
			}, nil
		}
		return nil, fmt.Errorf("failed to get article: %w", err)
	}

	_ = username
	return &model.ArticleSuccess{Article: articleToGraphQL(dbItem)}, nil
}

// Labels is the resolver for the labels field.
func (r *queryResolver) Labels(ctx context.Context) (model.LabelsResult, error) {
	// Get authenticated user
	user, hasUser := db.GetUserFromContext(ctx)
	if !hasUser {
		return &model.LabelsError{
			ErrorCodes: []model.LabelsErrorCode{model.LabelsErrorCodeUnauthorized},
		}, nil
	}

	userID, err := uuid.Parse(user.ID)
	if err != nil {
		return &model.LabelsError{
			ErrorCodes: []model.LabelsErrorCode{model.LabelsErrorCodeBadRequest},
		}, nil
	}

	// Fetch all labels for user
	labels, err := r.LabelRepo.GetByUserID(ctx, userID)
	if err != nil {
		return nil, fmt.Errorf("failed to fetch labels: %w", err)
	}

	// Convert to GraphQL models
	var gqlLabels []*model.Label
	for _, label := range labels {
		gqlLabels = append(gqlLabels, labelToGraphQL(*label))
	}

	return &model.LabelsSuccess{Labels: gqlLabels}, nil
}

// Highlights is the resolver for the highlights field.
func (r *queryResolver) Highlights(ctx context.Context, libraryItemID *string) ([]*model.Highlight, error) {
	// Get authenticated user
	user, hasUser := db.GetUserFromContext(ctx)
	if !hasUser {
		return nil, fmt.Errorf("unauthorized: no user in context")
	}

	userID, err := uuid.Parse(user.ID)
	if err != nil {
		return nil, fmt.Errorf("invalid user ID: %w", err)
	}

	var highlights []*dbmodel.Highlight

	if libraryItemID != nil {
		// Fetch highlights for specific library item
		itemID, err := uuid.Parse(*libraryItemID)
		if err != nil {
			return nil, fmt.Errorf("invalid library item ID: %w", err)
		}
		highlights, err = r.HighlightRepo.GetByLibraryItemID(ctx, itemID)
		if err != nil {
			return nil, fmt.Errorf("failed to fetch highlights: %w", err)
		}
	} else {
		// Fetch all highlights for user
		highlights, err = r.HighlightRepo.GetByUserID(ctx, userID)
		if err != nil {
			return nil, fmt.Errorf("failed to fetch highlights: %w", err)
		}
	}

	// Convert to GraphQL models
	var gqlHighlights []*model.Highlight
	for _, highlight := range highlights {
		gqlHighlights = append(gqlHighlights, highlightToGraphQL(*highlight))
	}

	return gqlHighlights, nil
}

// Subscriptions is the resolver for the subscriptions field.
func (r *queryResolver) Subscriptions(ctx context.Context, sort *model.SortParams, typeArg *dbmodel.SubscriptionType) ([]*dbmodel.Subscription, error) {
	// Get authenticated user
	user, hasUser := db.GetUserFromContext(ctx)
	if !hasUser {
		return nil, fmt.Errorf("unauthorized: no user in context")
	}

	userID, err := uuid.Parse(user.ID)
	if err != nil {
		return nil, fmt.Errorf("invalid user ID: %w", err)
	}

	// Set defaults
	sortBy := "updated_at"
	sortOrder := "DESC"
	if sort != nil {
		if sort.By != nil {
			sortBy = subscriptionSortBy(*sort.By)
		}
		if sort.Order != nil {
			sortOrder = subscriptionSortOrder(*sort.Order)
		}
	}

	// Fetch subscriptions
	subscriptions, err := r.SubscriptionRepo.FindByUserID(ctx, userID, typeArg, sortBy, sortOrder)
	if err != nil {
		return nil, fmt.Errorf("failed to fetch subscriptions: %w", err)
	}

	result := make([]*dbmodel.Subscription, 0, len(subscriptions))
	for i := range subscriptions {
		subscription := subscriptions[i]
		result = append(result, &subscription)
	}

	return result, nil
}

// Search is the resolver for the search field.
func (r *queryResolver) Search(ctx context.Context, after *string, first *int32, query *string, includeContent *bool) (model.SearchResult, error) {
	// Get authenticated user
	user, hasUser := db.GetUserFromContext(ctx)
	if !hasUser {
		return &model.SearchError{
			ErrorCodes: []model.SearchErrorCode{model.SearchErrorCodeUnauthorized},
		}, nil
	}

	userID, err := uuid.Parse(user.ID)
	if err != nil {
		return nil, fmt.Errorf("invalid user ID: %w", err)
	}

	searchQuery := ""
	if query != nil {
		searchQuery = *query
	}
	if len(searchQuery) > 1000 {
		return &model.SearchError{
			ErrorCodes: []model.SearchErrorCode{model.SearchErrorCodeQueryTooLong},
		}, nil
	}

	var firstInt *int
	if first != nil {
		value := int(*first)
		firstInt = &value
	}

	includeContentValue := false
	if includeContent != nil {
		includeContentValue = *includeContent
	}

	result, err := r.SearchService.Search(ctx, service.SearchParams{
		UserID:         userID,
		Query:          searchQuery,
		After:          after,
		First:          firstInt,
		IncludeContent: includeContentValue,
	})
	if err != nil {
		return nil, fmt.Errorf("failed to search library items: %w", err)
	}

	// Convert to edges
	edges := make([]*model.SearchItemEdge, len(result.Items))
	for i := range result.Items {
		item := result.Items[i]
		edges[i] = &model.SearchItemEdge{
			Cursor: item.ID.String(),
			Node:   libraryItemToGraphQL(&item),
		}
	}

	pageInfo := &model.PageInfo{
		HasNextPage:     result.HasNextPage,
		HasPreviousPage: result.HasPreviousPage,
		StartCursor:     result.StartCursor,
		EndCursor:       result.EndCursor,
	}
	if result.TotalCount != nil {
		totalCount := int32(*result.TotalCount)
		pageInfo.TotalCount = &totalCount
	}

	return &model.SearchSuccess{
		Edges:    edges,
		PageInfo: pageInfo,
	}, nil
}

// ID is the resolver for the id field.
func (r *subscriptionResolver) ID(ctx context.Context, obj *dbmodel.Subscription) (string, error) {
	return obj.ID.String(), nil
}

// NewsletterEmail is the resolver for the newsletterEmail field.
func (r *subscriptionResolver) NewsletterEmail(ctx context.Context, obj *dbmodel.Subscription) (*string, error) {
	if obj.NewsletterEmail == nil {
		return nil, nil
	}
	return &obj.NewsletterEmail.Address, nil
}

// Count is the resolver for the count field.
func (r *subscriptionResolver) Count(ctx context.Context, obj *dbmodel.Subscription) (int32, error) {
	return int32(obj.Count), nil
}

// LastFetchedAt is the resolver for the lastFetchedAt field.
func (r *subscriptionResolver) LastFetchedAt(ctx context.Context, obj *dbmodel.Subscription) (*string, error) {
	return formatTimePtr(obj.LastFetchedAt), nil
}

// CreatedAt is the resolver for the createdAt field.
func (r *subscriptionResolver) CreatedAt(ctx context.Context, obj *dbmodel.Subscription) (string, error) {
	return obj.CreatedAt.Format(time.RFC3339), nil
}

// UpdatedAt is the resolver for the updatedAt field.
func (r *subscriptionResolver) UpdatedAt(ctx context.Context, obj *dbmodel.Subscription) (*string, error) {
	return formatTimePtr(&obj.UpdatedAt), nil
}

// FetchContentType is the resolver for the fetchContentType field.
func (r *subscriptionResolver) FetchContentType(ctx context.Context, obj *dbmodel.Subscription) (model.FetchContentType, error) {
	switch strings.ToUpper(obj.FetchContentType) {
	case string(model.FetchContentTypeAlways):
		return model.FetchContentTypeAlways, nil
	case string(model.FetchContentTypeNever):
		return model.FetchContentTypeNever, nil
	case string(model.FetchContentTypeWhenEmpty):
		return model.FetchContentTypeWhenEmpty, nil
	default:
		return "", fmt.Errorf("unsupported fetch content type: %q", obj.FetchContentType)
	}
}

// MostRecentItemDate is the resolver for the mostRecentItemDate field.
func (r *subscriptionResolver) MostRecentItemDate(ctx context.Context, obj *dbmodel.Subscription) (*string, error) {
	return formatTimePtr(obj.MostRecentItemDate), nil
}

// RefreshedAt is the resolver for the refreshedAt field.
func (r *subscriptionResolver) RefreshedAt(ctx context.Context, obj *dbmodel.Subscription) (*string, error) {
	return formatTimePtr(obj.RefreshedAt), nil
}

// FailedAt is the resolver for the failedAt field.
func (r *subscriptionResolver) FailedAt(ctx context.Context, obj *dbmodel.Subscription) (*string, error) {
	return formatTimePtr(obj.FailedAt), nil
}

// Mutation returns generated.MutationResolver implementation.
func (r *Resolver) Mutation() generated.MutationResolver { return &mutationResolver{r} }

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

// Subscription returns generated.SubscriptionResolver implementation.
func (r *Resolver) Subscription() generated.SubscriptionResolver { return &subscriptionResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
type subscriptionResolver struct{ *Resolver }
